### ISSUE TITLE
Update - Additional Hostnames

### ISSUE THREAD

**Issue by westmyers** [takenek/NordVPN-IP-LIST#1]
Attached file containing additional hostnames (sorted) not already included in the current list.

Source: https://nordvpn.com/ovpn/
[Other NordVPN Hostnames.txt](https://github.com/takenek/NordVPN-IP-LIST/files/4870808/Other.NordVPN.Hostnames.txt)

**Comment by takenek** [comment]
Thanks!
Updated!
